# Recrée le schéma à chaque démarrage et le supprime à l'arrêt
# Pratique en dev : on repart toujours sur une base propre
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true

# Logs SQL pour faciliter le debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true