@baseUrl = http://localhost:3000

### REGISTER A NEW MEMBER
# EXPECTED: 200
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"player1@mail.com",
  "password":"123",
  "tag":"Vector",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITH EXISTING EMAIL
# EXPECTED: 409
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"player1@mail.com",
  "password":"123",
  "tag":"Duplicate",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITHOUT EMAIL
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "password":"123",
  "tag":"NoEmail",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITH EMPTY EMAIL
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"",
  "password":"123",
  "tag":"Test",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITHOUT PASSWORD
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"test@mail.com",
  "tag":"NoPassword",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITHOUT TAG
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"test2@mail.com",
  "password":"123",
  "specialtyId":1,
  "profileImageId":1
}

### REGISTER WITHOUT SPECIALTY
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"test3@mail.com",
  "password":"123",
  "tag":"Test"
}

### REGISTER WITHOUT PROFILE IMAGE
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email":"test4@mail.com",
  "password":"123",
  "tag":"Test",
  "specialtyId":1
}

### REGISTER WITH EMPTY BODY
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
}

### REGISTER WITH EMPTY REQUEST
# EXPECTED: 400
POST {{baseUrl}}/auths/register
Content-Type: application/json

### LOGIN SUCCESS
# EXPECTED: 200
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"player1@mail.com",
  "password":"123"
}

### LOGIN WITH WRONG PASSWORD
# EXPECTED: 401
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"player1@mail.com",
  "password":"WRONG"
}

### LOGIN WITH UNKNOWN USER
# EXPECTED: 401
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"unknown@mail.com",
  "password":"123"
}

### LOGIN WITHOUT EMAIL
# EXPECTED: 400
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "password":"123"
}

### LOGIN WITHOUT PASSWORD
# EXPECTED: 400
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"player1@mail.com"
}

### LOGIN WITH EMPTY EMAIL
# EXPECTED: 400
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"",
  "password":"123"
}

### LOGIN WITH EMPTY BODY
# EXPECTED: 400
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
}

### LOGIN WITH EMPTY REQUEST
# EXPECTED: 400
POST {{baseUrl}}/auths/login
Content-Type: application/json