@baseUrl = http://localhost:3000

# ----------- TEAM CREATION -----------

### 1: REGISTER A NEW MEMBER A
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "userA@test.com",
  "password": "Password123!",
  "tag": "UserA"
}

### 2: LOGIN USER A
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "userA@test.com",
  "password": "Password123!"
}

> {% client.global.set("tokenA", response.body.token); %}

### 3: Create a team (expect 201)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "My Team"
}

### 4: Create a team with duplicate name (expect 409)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "My Team"
}

### 5: Create a team without auth (expect 403)
POST {{baseUrl}}/teams/
Content-Type: application/json

{
  "name": "No Auth Team"
}

### 6: Create a team with blank name (expect 400)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "  "
}

### 7: Get Team details as a visitor
GET {{baseUrl}}/teams/1/details


# ----------- Quiting team Tests -----------

### 8: Quit team without being in a team (expect 400)
# Register a new member with no team
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "lonely@test.com",
  "password": "Password123!",
  "tag": "LonelyUser"
}

### Login with the new member
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "lonely@test.com",
  "password": "Password123!"
}

> {% client.global.set("auth_token_no_team", response.body.token); %}

### Try to quit a team whit no team (expect 400)
POST {{baseUrl}}/teams/quit
Content-Type: application/json
Authorization: {{auth_token_no_team}}

### 9: Quit team successfully (expect 200)
## Register a new member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "mana1@test.com",
  "password": "Password123!",
  "tag": "Mana1"
}

### Login with Mana1
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "mana1@test.com",
  "password": "Password123!"
}

> {% client.global.set("auth_token_manager1", response.body.token); %}

### Create a new team (expect 201)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{auth_token_manager1}}

{
  "name": "Team to leave"
}

### Quit the team as manager 1 with no other members reamaining (expect 200)
POST {{baseUrl}}/teams/quit
Content-Type: application/json
Authorization: {{auth_token_manager1}}

# ----------- Resign Manager Tests -----------

### 10: Resign as manager with NO replacement and NO other manager (expect 409)
PUT {{baseUrl}}/teams/1/resign
Authorization: {{auth_token_manager1}}

